Initial Tests
cathive/terraform-provider-concourse pull request #6
Opened 2018-09-27 10:36 UTC by NickLarsenNZ

I made some tests for the public method.

It only tests the code that deals with the flyrc set by environment variable.

2018-10-02 08:48 UTC, NickLarsenNZ commented
Hi @headcr4sh, have you had a chance to review? Are there changes you'd like me to make to be more inline with the Go norms?

2018-10-02 09:23 UTC, headcr4sh requested changes

2018-10-03 10:15 UTC, NickLarsenNZ commented on concourse/fly_config_test.go
> +	expected_test_file := "./test_fixtures/flyrc.yml"
Thanks for the tip. I've been reading more on Go conventions (I'm pretty new), so I'll circle around and fix up things that I haven't done ideally.

2018-10-03 19:27 UTC, headcr4sh approved these changes

2018-10-03 19:27 UTC, merged